CREATE TABLE IF NOT EXISTS pessoas (
    id INT(11) NOT NULL AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    telefone VARCHAR(15) NULL DEFAULT NULL,
    cpf VARCHAR(11) NOT NULL,
    endereco VARCHAR(255) NULL DEFAULT NULL,
    createdAt TIMESTAMP NULL DEFAULT current_timestamp(),
    updatedAt TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY cpf (cpf)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS movimentacao (
    id INT(11) NOT NULL AUTO_INCREMENT,
    idPessoa INT(11) NULL DEFAULT NULL,
    Credito DECIMAL(15,2) NULL DEFAULT NULL,
    Debito DECIMAL(15,2) NULL DEFAULT NULL,
    DataOperacao TIMESTAMP NULL DEFAULT current_timestamp(),
    Observacao VARCHAR(255) NULL DEFAULT NULL,
    CreatedAt TIMESTAMP NULL DEFAULT current_timestamp(),
    PRIMARY KEY (id),
    KEY FK_ID_PESSOA (idPessoa),
    CONSTRAINT FK_ID_PESSOA FOREIGN KEY (idPessoa) REFERENCES pessoas (id) ON UPDATE NO ACTION ON DELETE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS usuarios_faker (
    id INT(11) NOT NULL AUTO_INCREMENT,
    nome VARCHAR(100) DEFAULT NULL,
    sobrenome VARCHAR(100) DEFAULT NULL,
    email VARCHAR(150) DEFAULT NULL,
    telefone VARCHAR(50) DEFAULT NULL,
    endereco VARCHAR(255) DEFAULT NULL,
    cidade VARCHAR(100) DEFAULT NULL,
    cep VARCHAR(20) DEFAULT NULL,
    empresa VARCHAR(150) DEFAULT NULL,
    cargo VARCHAR(100) DEFAULT NULL,
    data_nascimento DATE DEFAULT NULL,
    numero_cartao VARCHAR(30) DEFAULT NULL,
    iban VARCHAR(50) DEFAULT NULL,
    uuid VARCHAR(36) DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
